### ISSUE TITLE
UpdraftPlus Backup Warning after activated the plugin

### ISSUE THREAD

**Issue by ansidev** [dipakcg/wp-performance-score-booster#22]
**Warning**: Your WordPress installation has a problem with outputting extra whitespace. This can corrupt backups that you download from here. [Follow this link for more information](https://updraftplus.com/problems-with-extra-white-space/)

**Comment by dipakcg** [comment]
This plugin is well tested with UpdraftPlus plugin. I have tested this plugin again now with active UpdraftPlus and didn't replicate such **Problems with extra white-space** issue. Hence, it looks like the culprit is something else.

As per UpdraftPlus article:

> If the problem is in none of your plugins, then it must be in some other part of your WordPress install, that has been modified from the default. Hunting it down can be frustrating – but it’s in there somewhere… you could also temporarily switch theme to a default theme (e.g. TwentyTwelve, TwentyThirteen). If that doesn’t find it, then try checking your wp-config.php file.

**Comment by ansidev** [comment]
I tested with the latest WP and two plugins, I tried to deactivate your plugin and the message gone away. If I activate your plugin, UpdraftPlus Backup/Restore will show the warning message.
